#!/usr/bin/env python3
"""Generate real Homebrew/Scoop metadata from completed, checksummed release assets."""
import argparse
import json
import re
from pathlib import Path
from tdlib_runtime import checksum

PLATFORMS = ('macos-aarch64', 'macos-x86_64', 'linux-aarch64', 'linux-x86_64', 'windows-x86_64')


def generate(repository, version, assets, destination):
    if not re.fullmatch(r'[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+', repository):
        raise ValueError('repository must be OWNER/REPO')
    if not re.fullmatch(r'\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?', version):
        raise ValueError('invalid version')
    assets, destination = Path(assets), Path(destination)
    base = f'https://github.com/{repository}'
    files = {platform: f'teleaf-{version}-{platform}.{"zip" if platform.startswith("windows-") else "tar.gz"}' for platform in PLATFORMS}
    hashes = {platform: checksum(assets / filename) for platform, filename in files.items()}
    lines = [f'{hashes[platform]}  {files[platform]}\n' for platform in sorted(files)]
    (assets / 'SHA256SUMS').write_text(''.join(lines))
    formula = [
        '# Generated by scripts/generate-packages.py; do not hand-edit checksums.',
        'class Teleaf < Formula',
        '  desc "Lightweight Telegram terminal client with inline media and mouse controls"',
        f'  homepage "{base}"',
        '  license "MIT"',
        f'  version "{version}"',
    ]
    for system in ('macos', 'linux'):
        formula.append(f'  on_{system} do')
        if system == 'macos':
            formula.append('    depends_on macos: :sequoia')
        for cpu, arch in (('arm', 'aarch64'), ('intel', 'x86_64')):
            platform = f'{system}-{arch}'
            formula.extend([f'    on_{cpu} do',
                f'      url "{base}/releases/download/v{version}/{files[platform]}"',
                f'      sha256 "{hashes[platform]}"', '    end'])
        formula.append('  end')
    formula.extend([
        '', '  def install', '    libexec.install Dir["*"]',
        '    bin.install_symlink libexec/"teleaf"', '  end', '',
        '  test do', '    assert_match "Teleaf #{version}", shell_output("#{bin}/teleaf --version")',
        '    assert_match "TDLib", shell_output("#{bin}/teleaf --check")', '  end', 'end', '',
    ])
    (destination / 'Formula').mkdir(parents=True, exist_ok=True)
    (destination / 'Formula/teleaf.rb').write_text('\n'.join(formula))
    manifest = {
        'version': version,
        'description': 'Lightweight Telegram terminal client with inline media and mouse controls',
        'homepage': base,
        'license': 'MIT',
        'architecture': {'64bit': {
            'url': f'{base}/releases/download/v{version}/{files["windows-x86_64"]}',
            'hash': hashes['windows-x86_64'],
        }},
        'bin': 'teleaf.exe',
        'checkver': 'github',
        'autoupdate': {'architecture': {'64bit': {
            'url': f'{base}/releases/download/v$version/teleaf-$version-windows-x86_64.zip',
            'hash': {'url': f'{base}/releases/download/v$version/SHA256SUMS', 'regex': '$sha256\\s+$basename'},
        }}},
    }
    (destination / 'bucket').mkdir(parents=True, exist_ok=True)
    (destination / 'bucket/teleaf.json').write_text(json.dumps(manifest, indent=4) + '\n')
    return destination / 'Formula/teleaf.rb', destination / 'bucket/teleaf.json'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repository', required=True)
    parser.add_argument('--version', required=True)
    parser.add_argument('--assets', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    for file in generate(args.repository, args.version, args.assets, args.output):
        print(file)
